In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('/Users/rose/Desktop/KG-for-Clinical-Guideline/data/CONCEPT_RELATIONSHIP.csv', sep='\t')
df.head()

,concept_id_1,concept_id_2,relationship_id,valid_start_date,valid_end_date,invalid_reason
0,4210800,40642538,Has status,20220128,20991231,NaN
1,4210800,40642539,Has Module,20220128,20991231,NaN
2,42535514,40642537,Has status,20220128,20991231,NaN
3,42535514,40642539,Has Module,20220128,20991231,NaN
4,40530649,40642538,Has status,20220128,20991231,NaN

In [6]:
df['relationship_id'].value_counts()

relationship_id
Mapped from             4451072
Maps to                 4451072
Has marketed form       2000405
Marketed form of        2000405
RxNorm has dose form    1797125
                         ...
Surface texture of            4
Surf character of             4
Has surface char              4
After                         1
Before                        1
Name: count, Length: 326, dtype: int64

In [17]:
# Maps to 관계를 가진 모든 행 필터링
maps_to_df = df[df['relationship_id'] == 'Maps to']
maps_to_df.head()

,concept_id_1,concept_id_2,relationship_id,valid_start_date,valid_end_date,invalid_reason
49956,45144491,42902856,Maps to,20180420,20991231,NaN
49971,45265026,19034832,Maps to,19700101,20991231,NaN
49972,45185309,19008026,Maps to,19700101,20991231,NaN
49973,45264994,19033377,Maps to,19700101,20991231,NaN
49974,45034816,715301,Maps to,20080602,20991231,NaN

In [11]:
df['relationship_id'].unique()

array(['Has status', 'Has Module', 'Plays role', 'Has due to', 'Is a',
       'Has focus', 'Has interprets', 'Has indir proc site',
       'Has brand name', 'Has finding site', 'Has clinical course',
       'Has interpretation', 'Has scale type', 'Has inherent loc',
       'Brand name of', 'Has occurrence', 'Has asso morph',
       'Has dir proc site', 'Has comp material', 'Is sterile',
       'Has absorbability', 'Has method', 'Has active ing',
       'Has temporal context', 'Has relat context', 'Followed by',
       'Inheres in', 'Has property', 'Has technique', 'Has disposition',
       'Has pathology', 'Has coating material', 'Has causative agent',
       'Has surgical appr', 'Has access', 'Maps to', 'Mapped from',
       'Finding asso with', 'Has dir device', 'Has laterality',
       'Has specimen topo', 'Has specimen subst', 'Has direct site',
       'Has dir morph', 'Has asso finding', 'SPL - RxNorm',
       'RxNorm - SPL', 'RxNorm has ing', 'Contains',
       'RxNorm has dose form', 'Form of', 'RxNorm inverse is a',
       'Has precise ing', 'Consists of', 'Tradename of', 'RxNorm is a',
       'Has tradename', 'Constitutes', 'Has dose form group',
       'Quantified form of', 'RxNorm dose form of', 'Has form',
       'RxNorm ing of', 'Contained in', 'Dose form group of',
       'Has quantified form', 'Precise ing of', 'Concept replaced by',
       'Concept replaces', 'Subsumes', 'SNOMED cat - CPT4',
       'SNOMED - CPT4 eq', 'Concept was_a from', 'Concept poss_eq from',
       'Concept same_as from', 'Interpretation of', 'Maps to value',
       'Asso finding of', 'Due to of', 'Asso with finding', 'Follows',
       'Focus of', 'Concept poss_eq to', 'Occurs after',
       'Value mapped from', 'Concept same_as to', 'Has finding context',
       'Concept alt_to from', 'Occurs before', 'Manifestation of',
       'Concept was_a to', 'Has manifestation', 'During',
       'Available as box', 'Using acc device', 'Has marketed form',
       'RxNorm - SNOMED eq', 'Has time aspect', 'Has Answer',
       'Has supplier', 'Box of', 'Marketed form of',
       'RxNorm - ATC pr lat', 'RxNorm - ATC sec up', 'Has component',
       'Type of service of', 'Kind of', 'Subject matter of', 'Setting of',
       'Role of', 'Has kind', 'Has type of service', 'Has system',
       'ATC - RxNorm pr lat', 'ATC - RxNorm sec lat', 'ATC - RxNorm',
       'Has asso proc', 'Has intent', 'Has specimen proc',
       'Using finding method', 'Dir device of', 'Has proc context',
       'Asso morph of', 'Dir subst of', 'Has dir subst',
       'Finding site of', 'Subst used by', 'Using subst', 'Asso proc of',
       'Using energy', 'Has route of admin', 'Supplier of',
       'RxNorm - ATC', 'RxNorm - ATC pr up', 'Method of',
       'Time aspect of', 'Panel contains', 'Contained in panel',
       'Has subject matter', 'Component of', 'System of', 'Property of',
       'Scale type of', 'Answer of', 'RxNorm - ATC sec lat',
       'Drug class of drug', 'Has proc site', 'Using device',
       'Has proc device', 'Has proc morph', 'Has recipient cat',
       'SNOMED - RxNorm eq', 'CPT4 - SNOMED eq', 'CPT4 - SNOMED cat',
       'CPT4 - LOINC eq', 'LOINC - CPT4 eq', 'Has role', 'Has setting',
       'Dir proc site of', 'Specimen topo of', 'Has specimen source',
       'Specimen of', 'Indir proc site of', 'Proc site of',
       'Causative agent of', 'Dir morph of', 'Interprets of',
       'Has specimen', 'Active ing of', 'Spec active ing of',
       'Modification of', 'Basis str subst of', 'Prec ingredient of',
       'Concept alt_to to', 'Specimen subst of', 'Device used by',
       'Disp dose form of', 'Surgical appr of', 'Access of',
       'Specimen proc of', 'Indir morph of', 'Route of',
       'Specimen identity of', 'Has dose form', 'Specimen morph of',
       'Proc morph of', 'Has indir morph', 'Has modification',
       'Temporal context of', 'Property type of', 'Proc device of',
       'Has dose form unit', 'Has unit of prod use',
       'Has spec active ing', 'Has denominator unit',
       'Has numerator unit', 'Has indir device', 'Has conc denom unit',
       'Has basis str subst', 'Has disp dose form', 'Has route',
       'SNOMED - ATC eq', 'Has prec ingredient', 'Proc duration of',
       'Has priority', 'Clinical course of', 'Count of ing of',
       'Denom value of', 'Numerator value of', 'Conc num val of',
       'Energy used by', 'Laterality of', 'Acc device used by',
       'Finding method of', 'Revision status of', 'Conc num unit of',
       'Unit of admin of', 'Conc denom unit of', 'Has specimen morph',
       'Numerator unit of', 'Dose form unit of', 'Denominator unit of',
       'Relat context of', 'Intent of', 'Finding context of',
       'Has unit of presen', 'Has conc num unit', 'Route of admin of',
       'Has intended site', 'Occurrence of', 'Pathology of',
       'Has count of ing', 'Dose form of', 'Recipient cat of',
       'Technique of', 'Has unit of admin', 'Proc context of',
       'Has numerator value', 'Has complication', 'Has inherent',
       'Priority of', 'Unit of prod use of', 'Has conc num val',
       'Has basic dose form', 'Has state of matter', 'Has transformation',
       'Indir device of', 'Basic dose form of', 'Has admin method',
       'Drug has drug class', 'ATC - SNOMED eq', 'ATC - RxNorm sec up',
       'ATC - RxNorm pr up', 'Admin method of', 'Has denomin value',
       'Disposition of', 'Intended site of', 'Role played by',
       'Status of', 'Towards', 'Relative to', 'Temp related to',
       'Process extends to', 'Characterizes', 'Process acts on',
       'Module of', 'Subject of', 'Relative to of', 'Unit of presen of',
       'Has temp finding', 'Process extends from', 'Inherent location of',
       'Is characterized by', 'Affected by process', 'Has asso visit',
       'Asso visit of', 'Has proc duration', 'Has unit',
       'Precoord pair of', 'Has precoord pair', 'Unit of',
       'State of matter of', 'Transformation of', 'Is sterile of',
       'Absorbability of', 'Dev intended site of', 'Comp material of',
       'Targ population of', 'Coating material of', 'Direct site of',
       'Version contains', 'Contained in version', 'Has dev intend site',
       'Before', 'After', 'Has property type', 'Has precondition',
       'Precondition of', 'Has prod character', 'Prod character of',
       'Has targ population', 'Has measurement', 'Process output of',
       'Finding inform of', 'Conc denom val of', 'Has release charact',
       'Release charact of', 'Has process output', 'Count of act ing in',
       'Relative part of', 'Severity of', 'Measurement of', 'Strength of',
       'Using finding inform', 'Has count of act ing', 'Filling of',
       'Has revision status', 'Has conc denom val', 'Has surface texture',
       'Surface texture of', 'Surf character of', 'Has surface char',
       'Has strength', 'Has relative part', 'Has severity', 'Has filling'],
      dtype=object)

In [16]:
df[df['concept_id_1'] == 4078821]

,concept_id_1,concept_id_2,relationship_id,valid_start_date,valid_end_date,invalid_reason
7278337,4078821,40642538,Has status,20220128,20991231,NaN
7278338,4078821,40642539,Has Module,20220128,20991231,NaN
17089412,4078821,4311405,Concept replaced by,20220930,20991231,NaN
17131515,4078821,4311405,Maps to,20230927,20991231,NaN